services:
  spark:
    image: lha151105/spark:latest
    command: ["tail", "-f", "/dev/null"]
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
      - '6066:6066'
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
  spark-worker:
    image: lha151105/spark:latest
    command: ["tail", "-f", "/dev/null"]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '28081:8081'
      - '24040:4040'
      - '24041:4041'
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
  data-source:
    image: lha151105/python:latest
    environment:
      - TOKEN=your_api_token_here
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
    ports:
      - "9999:9999"
    command: python3.9 -u /streaming/data_source.py
  webapp:
    image: lha151105/python:latest
    volumes:
      - D:/GitHub-Real-time-Analytics/streaming:/streaming
    ports:
      - '5000:5000'
    command: bash -c "pip3.9 install flask redis matplotlib && cd /streaming/webapp && python3.9 web_app.py"
  redis:
    image: lha151105/redis:latest
    ports:
      - '6379:6379'
